[package]
name = "vox"
version = "0.3.5"
edition = "2021"
rust-version = "1.71"
description = "A systems level compiler for Vox (sentence based code)"
license = "GPL-3.0-or-later"

[dependencies]
thiserror = "2.0"

[profile.release]
opt-level = 3
lto = true

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/vox", dest = "/usr/bin/vox", mode = "755" },
    { source = "coreasm/**/*", dest = "/usr/share/vox/coreasm/", mode = "644" },
    { source = "LICENSE", dest = "/usr/share/doc/vox/LICENSE", mode = "644", doc = true },
    { source = "README.md", dest = "/usr/share/doc/vox/README.md", mode = "644", doc = true },
]
